import type { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    slug: 'quiet-hours',
    name: 'Quiet Hours',
    collection: 'monochrome',
    template: 'typographic',
    params: { text: 'QUIET', weight: 700, align: 'start', scale: 1.05, rule: true },
    palettes: ['paper', 'ink'],
    basePriceCents: 2900,
    tags: ['type', 'word', 'minimal'],
    featured: true,
    description: 'One word set large, with a hairline underneath. The kind of poster that does the talking for an empty wall.',
  },
  {
    slug: 'ninety-six',
    name: 'Ninety-Six',
    collection: 'monochrome',
    template: 'grid',
    params: { columns: 8, rows: 12, density: 0.7, seed: 11 },
    palettes: ['paper', 'ink'],
    basePriceCents: 2600,
    tags: ['grid', 'geometric'],
    description: 'Ninety-six cells, some filled, some left open.',
  },
  {
    slug: 'low-tide',
    name: 'Low Tide',
    collection: 'monochrome',
    template: 'orbit',
    params: { rings: 9, offset: 0.35, seed: 3 },
    palettes: ['ink', 'paper'],
    basePriceCents: 3100,
    tags: ['circles', 'orbit', 'calm'],
    featured: true,
    description: 'Nine rings drifting off centre. Reads as water from across the room and as geometry up close.',
  },
  {
    slug: 'sixteen-lines',
    name: 'Sixteen Lines',
    collection: 'monochrome',
    template: 'stripes',
    params: { count: 16, angle: 0, numeral: '16' },
    palettes: ['paper', 'ink'],
    basePriceCents: 2400,
    tags: ['stripes', 'lines', 'numeral'],
    description: 'Sixteen horizontal bands and a numeral. Plain, deliberate, easy to live with.',
  },
  {
    slug: 'red-corner',
    name: 'Red Corner',
    collection: 'primary',
    template: 'blocks',
    params: { layout: 'corner', seed: 5 },
    palettes: ['signal', 'paper', 'ocean'],
    basePriceCents: 3300,
    tags: ['blocks', 'bauhaus', 'red'],
    featured: true,
    description: 'A quarter circle pinned in the corner and three rectangles keeping their distance. Loud in red, calm in paper.',
  },
  {
    slug: 'seven-diagonals',
    name: 'Seven Diagonals',
    collection: 'primary',
    template: 'stripes',
    params: { count: 7, angle: 30, numeral: '7' },
    palettes: ['ocean', 'signal', 'paper'],
    basePriceCents: 2800,
    tags: ['stripes', 'diagonal', 'numeral'],
    description: 'Seven bands at thirty degrees with a large seven riding across them.',
  },
  {
    slug: 'loud',
    name: 'Loud',
    collection: 'primary',
    template: 'typographic',
    params: { text: 'LOUD', weight: 700, align: 'middle', scale: 1.1, rule: false },
    palettes: ['signal', 'ocean'],
    basePriceCents: 2900,
    tags: ['type', 'word', 'bold'],
    description: 'Four letters at full width. Say it with your wall.',
  },
  {
    slug: 'nine-by-twelve',
    name: 'Nine by Twelve',
    collection: 'primary',
    template: 'grid',
    params: { columns: 9, rows: 12, density: 0.55, seed: 21 },
    palettes: ['ocean', 'signal', 'paper'],
    basePriceCents: 2600,
    tags: ['grid', 'circles', 'squares'],
    featured: true,
    description: 'A nine-by-twelve grid where circles and squares take turns. Busy from a distance, orderly up close, and it changes character completely between navy and paper.',
  },
  {
    slug: 'morning-orbit',
    name: 'Morning Orbit',
    collection: 'pastel',
    template: 'orbit',
    params: { rings: 6, offset: 0.2, seed: 8 },
    palettes: ['sage', 'sand', 'paper'],
    basePriceCents: 3100,
    tags: ['circles', 'orbit', 'soft'],
    featured: true,
    description: 'Six soft rings on sage green, offset just enough to feel hand-placed.',
  },
  {
    slug: 'sand-blocks',
    name: 'Sand Blocks',
    collection: 'pastel',
    template: 'blocks',
    params: { layout: 'stack', seed: 13 },
    palettes: ['sand', 'sage'],
    basePriceCents: 3300,
    tags: ['blocks', 'warm', 'stacked'],
    description: 'Stacked rectangles in warm sand tones. A quiet composition for a bedroom or a hallway.',
  },
  {
    slug: 'sparse',
    name: 'Sparse',
    collection: 'pastel',
    template: 'grid',
    params: { columns: 6, rows: 9, density: 0.35, seed: 34 },
    palettes: ['sage', 'sand', 'paper'],
    basePriceCents: 2600,
    tags: ['grid', 'minimal', 'empty'],
    description: 'A six-by-nine grid mostly left empty. The gaps are the point.',
  },
  {
    slug: 'slow',
    name: 'Slow',
    collection: 'pastel',
    template: 'typographic',
    params: { text: 'SLOW', weight: 400, align: 'end', scale: 1.0, rule: true },
    palettes: ['sand', 'sage'],
    basePriceCents: 2900,
    tags: ['type', 'word', 'light'],
    description: 'Set light, aligned right, with a rule under it. For rooms where nothing needs to happen fast.',
  },
  {
    slug: 'after-dark',
    name: 'After Dark',
    collection: 'night',
    template: 'stripes',
    params: { count: 24, angle: 90, numeral: '24' },
    palettes: ['ink', 'ocean'],
    basePriceCents: 2400,
    tags: ['stripes', 'vertical', 'numeral'],
    featured: true,
    description: 'Twenty-four vertical bands and the number of hours in a day.',
  },
  {
    slug: 'far-orbit',
    name: 'Far Orbit',
    collection: 'night',
    template: 'orbit',
    params: { rings: 12, offset: 0.5, seed: 17 },
    palettes: ['ink', 'ocean'],
    basePriceCents: 3100,
    tags: ['circles', 'orbit', 'dark'],
    description: 'Twelve rings pushed far off centre on a black ground. The largest one runs off the edge, which is where it belongs.',
  },
  {
    slug: 'night-blocks',
    name: 'Night Blocks',
    collection: 'night',
    template: 'blocks',
    params: { layout: 'split', seed: 29 },
    palettes: ['ocean', 'ink'],
    basePriceCents: 3300,
    tags: ['blocks', 'navy', 'split'],
    description: 'A split composition in navy: two big fields, one quarter circle, one warm accent.',
  },
  {
    slug: 'hush',
    name: 'Hush',
    collection: 'night',
    template: 'typographic',
    params: { text: 'HUSH', weight: 700, align: 'start', scale: 1.1, rule: false },
    palettes: ['ink', 'ocean'],
    basePriceCents: 2900,
    tags: ['type', 'word', 'dark'],
    description: 'Bold letters on black.',
  },
]

export function productBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug)
}

export function requireProduct(slug: string): Product {
  const product = productBySlug(slug)
  if (!product) throw new Error(`Unknown product slug: ${slug}`)
  return product
}
